services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - cybergarden-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./backend/database_save:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - cybergarden-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  database-service:
    build:
      context: ./backend/database 
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/database/app.log:/app/app.log
    expose:
      - 2012
    networks:
      - cybergarden-net
    depends_on:
      db:
        condition: service_healthy

  bot:
    build:
      context: ./backend/bot
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/bot/app.log:/app/app.log
    ports:
      - 8081:8081
    expose:
      - 2011
    networks:
      - cybergarden-net

  ollama:
    image: ollama/ollama:latest
    container_name: gemma_engine
    volumes:
      - ollama_data:/root/.ollama
    expose:
      - 11434
    networks:
      - cybergarden-net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
  

  ollama-init: 
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - cybergarden-net
    command: ollama pull gemma3
    depends_on:
      ollama:
        condition: service_healthy

  ml-service:
    build:
      context: ./backend/ml
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434/api/chat
      - MODEL_NAME=gemma3
      - PORT=8082
    expose:
      - 8082
    networks:
      - cybergarden-net
    depends_on:
      ollama-init:
        condition: service_completed_successfully
      ollama:
        condition: service_started

  manager:
    build:
      context: ./backend/manager
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/manager/app.log:/app/app.log
    ports:
      - "8080:8080"
    networks:
      - cybergarden-net
    depends_on:
      - bot
      - database-service
      - ml-service

volumes:
  ollama_data:
  
networks:
  cybergarden-net:
    driver: bridge