services:

  frontend:
    build:
      context: ./backend/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - cybergarden-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./backend/database_save:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - cybergarden-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  database-service:
    build:
      context: ./backend/database 
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 2012
    networks:
      - cybergarden-net
    depends_on:
      db:
        condition: service_healthy

  bot:
    build:
      context: ./backend/bot
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/bot/app.log:/app/app.log
    ports:
      - 8081:8081
    expose:
      - 2011
    networks:
      - cybergarden-net

  manager:
    build:
      context: ./backend/manager
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - cybergarden-net
    depends_on:
      - bot
      - database-service